export default [
  { col: 'log_nr_', note: 'log_nr_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: true, nullable: true, insert: false, edit: true, list: false, search: true, searchMode: '=', uiType: 'input', distType: '', sort: '1' },
  { col: 'type_', note: 'type_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: true, nullable: false, insert: true, edit: true, list: false, search: false, searchMode: '!=', uiType: 'input', distType: '', sort: '2' },
  { col: 'proc_def_id_', note: 'proc_def_id_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: false, nullable: true, insert: true, edit: true, list: false, search: false, searchMode: '>', uiType: 'checkbox', distType: '', sort: '3' },
  { col: 'proc_inst_id_', note: 'proc_inst_id_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: false, nullable: false, insert: true, edit: false, list: true, search: true, searchMode: '<=', uiType: 'dateselect', distType: '', sort: '4' },
  { col: 'execution_id_', note: 'execution_id_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: false, nullable: false, insert: false, edit: false, list: true, search: true, searchMode: 'between', uiType: 'officeselect', distType: '', sort: '5' },
  { col: 'task_id_', note: 'task_id_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: false, nullable: false, insert: false, edit: false, list: true, search: true, searchMode: 'left_like', uiType: 'treeselect', distType: '', sort: '6' },
  { col: 'time_stamp_', note: 'time_stamp_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: true, nullable: true, insert: false, edit: true, list: false, search: true, searchMode: '=', uiType: 'input', distType: '', sort: '7' },
  { col: 'user_id_', note: 'user_id_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: true, nullable: false, insert: true, edit: true, list: false, search: false, searchMode: '!=', uiType: 'input', distType: '', sort: '8' },
  { col: 'data_', note: 'data_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: false, nullable: true, insert: true, edit: true, list: false, search: false, searchMode: '>', uiType: 'checkbox', distType: '', sort: '9' },
  { col: 'lock_owner_', note: 'lock_owner_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: false, nullable: false, insert: true, edit: false, list: true, search: true, searchMode: '<=', uiType: 'dateselect', distType: '', sort: '10' },
  { col: 'lock_time_', note: 'lock_time_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: false, nullable: false, insert: false, edit: false, list: true, search: true, searchMode: 'between', uiType: 'officeselect', distType: '', sort: '11' },
  { col: 'is_processed_', note: 'is_processed_', type: 'bigint(20)', javaType: 'Long', javaAttr: 'logNr', mainKey: false, nullable: false, insert: false, edit: false, list: true, search: true, searchMode: 'left_like', uiType: 'treeselect', distType: '', sort: '12' }
]
